databases:
  - name: servidorBrandon
    plan: free
    databaseName: dbcine
    user: brandon

services:
  - type: web
    plan: free
    name: cineUtc
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cineUtc.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: servidorBrandon
          property: externalConnectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: cineutc-sasy.onrender.com



# set DATABASE_URL=postgresql://brandon:38MD0TnCONLjk0r9pCBrIvfbRqzfSOI3@dpg-cqlpttg8fa8c73bikmm0-a.oregon-postgres.render.com/dbcine_g3h2